[HIMDBVersion]
2.0
[DATABASE_VERSION]
"1.1" 
[SESSIONS_]
"SessionR8C_E8_SYSTEM" 
[CONFIGURATIONS]
"Debug_R8C_E8_SYSTEM" 
"Rel_1_6_1_024" 
"Release" 
[CURRENT_CONFIGURATION]
"Debug_R8C_E8_SYSTEM" 
[CURRENT_SESSION]
"SessionR8C_E8_SYSTEM" 
[GENERAL_DATA_PROJECT]
[GENERAL_DATA_CONFIGURATION_Debug_R8C_E8_SYSTEM]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_Debug_R8C_E8_SYSTEM]
"SessionR8C_E8_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_Rel_1_6_1_024]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Rel_1_6_1_024]
"SessionR8C_E8_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_Release]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Release]
"SessionR8C_E8_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_SESSION_Rel_1_6_1_024_SessionR8C_E8_SYSTEM]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_R8C_E8_SYSTEM_SessionR8C_E8_SYSTEM]
[GENERAL_DATA_CONFIGURATION_SESSION_Release_SessionR8C_E8_SYSTEM]
[GENERAL_DATA_SESSION_SessionR8C_E8_SYSTEM]
[END]
